# Generated by Django 4.0.1 on 2022-01-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('closed', models.BooleanField(default=False)),
                ('created_user', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'time_from', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('name', 'date'), name='unique calendar rule'),
        ),
    ]
