# Generated by Django 4.0.1 on 2022-01-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendar', '0002_alter_appointment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='closed',
        ),
    ]
