# Generated by Django 4.0.1 on 2022-01-25 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grocery_store', '0002_einkaufsliste_erledigt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='einkaufsliste',
            options={'ordering': ['erledigt', 'beschreibung']},
        ),
        migrations.AlterField(
            model_name='einkaufsliste',
            name='anzahl',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
